apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres
    url: postgres:5432
    database: iot
    user: root
    access: proxy
    isDefault: false
    editable: true
    secureJsonData:
      password: secret
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true